########################################################################
# AUTHOR: Hiep Phuc Thai                                               #
# It takes me 2 years to finish this shiet, but it's worth every penny #
# It's not just about the implementation, it's about the idea also     #
########################################################################

set-option -g set-clipboard on

set-option -g renumber-windows on

# Settings to work with Neovim
set-option -sg escape-time 0
set-option -g focus-events on
set-option -g default-terminal "xterm-256color"
set-option -as terminal-features ',xterm-256color:RGB'

set-option -g mouse off

# Unlimit history
set-option -g history-limit 9999999

# Set key mode to vi
setw -g mode-keys vi

# Patnes settings
set-option -g pane-active-border-style bg=default,fg=color201
set-option -g pane-border-style bg=default,fg=color241
set-option -g pane-border-lines "heavy"
set-option -g pane-border-indicators "both"

# Source configuration easily
bind-key r source-file ~/.tmux.conf

# Panes synchronization
bind-key e set-window-option synchronize-pane

# Swap windows but still keep focus on current window
bind-key -r C-n swap-window -d -t +1
bind-key -r C-p swap-window -d -t -1

# Copy mode settings
bind-key P paste-buffer
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set-option -g status-justify centre
set-option -g status-keys vi

# List of plugins
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sessionist'
set-option -g @plugin 'b0o/tmux-autoreload'
set-option -g @plugin 'sainnhe/tmux-fzf'
set-option -g @plugin 'tmux-plugins/tmux-resurrect'
set-option -g @plugin 'tmux-plugins/tmux-continuum'
set-option -g @plugin 'tphiepbk/tmux-double-status-bar'
set-option -g @plugin 'tphiepbk/tmux-no-pane-cycle'

# Configuration for tmux-autoreload plugin
set-option -g @tmux-autoreload-quiet 1

# Double status bar separator style
set-option -g @double-status-bar-separator-style 'half_round'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

